language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
