language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token:
      secure: rU0Z3tvOr906MShmITkgKi2j/H2V2g4Si3HbDhUnySQesuOG2QccytuUoVvX+lHrhAFuUiJDjzuvzRIzRL//YABN92qvn4xdxbY0X0AvsjgeO8CbrEoZ6dC656dKciRlKZR2RI7HhS1UPe37P7dDVtakqaUJBsVYRLXIUERyNMkoCtSjzgGhx4/4pT087ThcrCcOTLBdQZenV4MgM6hcW5rUA03YsHnfOEfxclGGi9TEqFLVEFlrbFv4M1nsYogAZ3o6xZ2an86nuChMhef/2jOeuvawdz34MBOa/92dLlD9CsJY/1HSVWDpWjwYketkI/0GUcwJmGcUwLEv9esPkY6R9ZEDT9PfjBJsJDy3JC6XIamvjhT32I7pwvHydgGA26YQIULtQNF51EP4eU6a06N1V2U/JtAx1/m+0pJ6Lf1CuYOHXyf6WJ+evlqOvNgmPhuNABSvQfvn6H1L1nIHBUQ9FJ11qWXqzh2nO/nwYU2TCQn9ogtRQxClTNQm4/06XwGwn4Xy6TNulhygoYOshMxqR8yo3g+giKPNTh0dXA7GSawA4S8ZcRS5ZnQih9xyw5V0XssGTNsCgS+P2RwUOEq1zNke/KJaNuN789s9ewaSc4TABj5abF/KgzgEEvHvrFbTeJHL0eungJW/6Req8Ayt8hakUoYz5eGXHxGQd5g=
